language: generic
matrix:
  include:
  - env: GO_VERSION=1.9
  - env: GO_VERSION=rc
  allow_failures:
    - env: GO_VERSION=rc
  fast_finish: true
sudo: required
services:
- docker
cache:
  directories:
    - $GOPATH/pkg/dep
stages:
  - test
  - name: deploy
    if: type != pull_request
jobs:
  include:
    # Test
    - script: make verify build build-integration build-e2e test images svcat
    # Deploy
    - stage: deploy
      env:
        -  GO_VERSION=1.9
      deploy:
        skip_cleanup: true
        provider: script
        script: contrib/travis/deploy.sh
        on:
          repo: kubernetes-incubator/service-catalog
          all_branches: true
