language: generic
sudo: required
services:
- docker
cache:
  directories:
  - .glide
script:
- make test-e2e
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    repo: kubernetes-incubator/service-catalog
    branch: master
